env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
    project: ./tsconfig.json
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - 'jsx-a11y'
rules: {
  sort-imports: 0,
  import/order: [2, { alphabetize: { order: asc } }],
  react-hooks/rules-of-hooks: error,
  react-hooks/exhaustive-deps: warn,
  react/react-in-jsx-scope: off
}
